import { useEffect, useRef, useState } from 'react';
import { MessageCircle, X, Send, Bot } from 'lucide-react';
import { sendChatMessage, type ChatHistoryItem } from '@/lib/api';

type Message = { role: 'user' | 'assistant'; content: string };
const welcome: Message = { role: 'assistant', content: 'Hi! I’m the Devigners assistant. Ask me about CUBE, COHORT, admissions, or learning at Devigners.' };

export default function ChatWidget() {
  const [open, setOpen] = useState(false); const [input, setInput] = useState(''); const [loading, setLoading] = useState(false); const [messages, setMessages] = useState<Message[]>([welcome]); const endRef = useRef<HTMLDivElement>(null);
  useEffect(() => endRef.current?.scrollIntoView({ behavior: 'smooth' }), [messages]);
  const send = async (e: React.FormEvent) => { e.preventDefault(); const text = input.trim(); if (!text || loading) return; const next = [...messages, { role: 'user' as const, content: text }]; setMessages(next); setInput(''); setLoading(true); try { const history: ChatHistoryItem[] = next.slice(1).map((m) => ({ role: m.role, content: m.content })); const result = await sendChatMessage(text, history.slice(0, -1)); setMessages((prev) => [...prev, { role: 'assistant', content: result.reply }]); } catch { setMessages((prev) => [...prev, { role: 'assistant', content: 'I’m unable to connect right now. Please use the Contact page for admissions questions.' }]); } finally { setLoading(false); } };
  return <div className="fixed bottom-5 right-5 z-40 flex flex-col items-end"><div className={`mb-3 w-[calc(100vw-2.5rem)] max-w-sm overflow-hidden rounded-2xl border border-slate-200 bg-white shadow-2xl ${open ? '' : 'hidden'}`}><div className="flex items-center justify-between bg-red-600 px-4 py-3 text-white"><div className="flex items-center gap-2 font-extrabold"><Bot className="h-4 w-4" /> Devigners Assistant</div><button onClick={() => setOpen(false)} aria-label="Close chat"><X className="h-5 w-5" /></button></div><div className="h-80 space-y-3 overflow-y-auto p-4">{messages.map((m, i) => <div key={i} className={`max-w-[85%] rounded-2xl px-3.5 py-2.5 text-sm leading-6 ${m.role === 'user' ? 'ml-auto bg-red-600 text-white' : 'bg-slate-100 text-slate-700'}`}>{m.content}</div>)}{loading && <div className="w-fit rounded-2xl bg-slate-100 px-3.5 py-2.5 text-sm text-slate-500">Thinking…</div>}<div ref={endRef} /></div><form onSubmit={send} className="flex gap-2 border-t border-slate-100 p-3"><input value={input} onChange={(e) => setInput(e.target.value)} className="field" placeholder="Ask a question…" /><button disabled={!input.trim() || loading} className="grid h-11 w-11 shrink-0 place-items-center rounded-xl bg-red-600 text-white disabled:opacity-40" aria-label="Send"><Send className="h-4 w-4" /></button></form></div><button onClick={() => setOpen((v) => !v)} className="grid h-14 w-14 place-items-center rounded-full bg-red-600 text-white shadow-xl shadow-red-600/30 hover:bg-red-700" aria-label="Open chat">{open ? <X /> : <MessageCircle />}</button></div>;
}
