import { Link } from 'react-router-dom';
import { ArrowRight, Computer, FolderOpen, Globe2, Keyboard, ShieldCheck, Sparkles } from 'lucide-react';

const modules = [
  ['Computer Basics', 'Understand what computers are, how they work, and the role of hardware and software.'],
  ['Windows & File Skills', 'Learn the desktop, settings, files, folders, storage and everyday organization.'],
  ['Internet & Email', 'Build practical internet, browser, search and email skills for daily study and work.'],
  ['Productivity Tools', 'Get comfortable with documents, presentations, spreadsheets and common digital workflows.'],
  ['Digital Safety', 'Learn responsible online habits, account safety, privacy and safe browsing fundamentals.'],
  ['Confidence Through Practice', 'Turn every lesson into hands-on practice so basic computer tasks feel natural.'],
];

export default function Cube() {
  return <ProgramPage badge="CUBE PROGRAM" title={<>Build your <span className="text-red-600">computer foundation.</span></>} intro="CUBE is designed for students who have little or no experience with computers. We start from the beginning and build the practical skills needed for confident digital learning." icon={<Computer className="h-8 w-8" />} cta="Ask about CUBE" href="/contact">
    <section className="bg-white py-20"><div className="mx-auto max-w-7xl px-5 lg:px-8"><div className="grid gap-6 md:grid-cols-2 lg:grid-cols-3">{modules.map(([title, text], i) => <div key={title} className="rounded-2xl border border-slate-200 bg-white p-6 shadow-sm hover:-translate-y-1 hover:border-red-200 hover:shadow-lg"><div className="grid h-11 w-11 place-items-center rounded-xl bg-red-50 font-black text-red-600">0{i + 1}</div><h3 className="mt-5 text-xl font-extrabold text-slate-950">{title}</h3><p className="mt-2 text-sm leading-7 text-slate-600">{text}</p></div>)}</div></div></section>
    <section className="bg-slate-950 py-20 text-white"><div className="mx-auto grid max-w-7xl gap-12 px-5 lg:grid-cols-2 lg:px-8"><div><p className="eyebrow eyebrow-dark">Who CUBE is for</p><h2 className="section-title text-white">A simple start for complete beginners.</h2><p className="section-copy text-slate-300">You do not need a programming background. CUBE is the place to become comfortable with the computer before moving into advanced technology learning.</p></div><div className="grid gap-4 sm:grid-cols-2">{[[Keyboard, 'Everyday computer use'], [FolderOpen, 'Files & organization'], [Globe2, 'Internet essentials'], [ShieldCheck, 'Digital safety']].map(([Icon, text]) => { const I = Icon as typeof Keyboard; return <div key={text as string} className="rounded-2xl border border-white/10 bg-white/5 p-5"><I className="h-6 w-6 text-red-400" /><p className="mt-4 font-extrabold">{text as string}</p></div>; })}</div></div></section>
  </ProgramPage>;
}

function ProgramPage({ badge, title, intro, icon, cta, href, children }: { badge: string; title: React.ReactNode; intro: string; icon: React.ReactNode; cta: string; href: string; children: React.ReactNode }) {
 return <div><section className="relative overflow-hidden bg-slate-50 pt-32"><div className="absolute right-0 top-0 h-96 w-96 rounded-full bg-red-100 blur-3xl" /><div className="relative mx-auto max-w-7xl px-5 pb-20 lg:px-8"><div className="max-w-3xl"><div className="mb-6 inline-flex items-center gap-2 rounded-full border border-red-100 bg-white px-4 py-2 text-xs font-extrabold uppercase tracking-[0.18em] text-red-600"><Sparkles className="h-4 w-4" /> {badge}</div><h1 className="text-5xl font-black leading-tight text-slate-950 sm:text-6xl">{title}</h1><p className="mt-6 max-w-2xl text-lg leading-8 text-slate-600">{intro}</p><div className="mt-8 flex flex-col gap-3 sm:flex-row"><Link to={href} className="inline-flex items-center justify-center gap-2 rounded-xl bg-red-600 px-6 py-3.5 font-extrabold text-white hover:bg-red-700">{cta} <ArrowRight className="h-4 w-4" /></Link><Link to="/cohort" className="inline-flex items-center justify-center gap-2 rounded-xl border-2 border-slate-200 bg-white px-6 py-3.5 font-extrabold text-slate-700 hover:border-red-200 hover:text-red-600">See the pathway</Link></div></div><div className="mt-12 grid max-w-md grid-cols-1 gap-3 sm:grid-cols-3 lg:absolute lg:right-8 lg:top-32 lg:mt-0">{['Beginner friendly', 'Hands-on practice', 'Clear next step'].map((t) => <div key={t} className="rounded-2xl border border-white bg-white p-4 shadow-lg"><div className="mb-2 text-red-600">{icon}</div><p className="text-sm font-extrabold text-slate-800">{t}</p></div>)}</div></div></section>{children}</div>;
}
